config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,controllers: {registrations: "registrations"}
  root 'users#index'
  resources :admins 
  resources :customers ,:shopkeepers 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope'admin' do
    resources :users do
      collection do  
        post 'confirm_order'
        post 'update_user'
      end
    resources :orders    
    end    
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many   :shopkeepers 
end

app/models/shopkeeper.rb
class Shopkeeper < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum user_type: [:customer,:shopkeeper,:admin,:user]
  scope :all_except, ->(user) { where.not(id: user) }
  has_many :orders
  
  after_create :send_email

  def send_email
    ConfirmationMailer.confirmation_email(self).deliver
  end       
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def index
    @users = User.all_except(current_user)        
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,
:phone_no,:user_type])
  end

  def after_sign_in_path_for(resource)
    if resource.admin? 
      admins_path
    elsif resource.shopkeeper?
      shopkeepers_path         
    else 
      request.env['omniauth.origin'] || stored_location_for(resource) ||  root_path 
    end   
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!

  def index
    @order = User.where(user_type:0)
  end  



  def show 
  end  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:new]  
  skip_before_action :require_no_authentication, only: [:new,:create]
  
  protected
  
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/shopkeepers_controller.rb
class ShopkeepersController < ApplicationController  
  
  def index
    debugger
    @users = User.where(user_type: 0)
  end  
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index

  end
  
  def show
  end

  def new 
    @user = User.new
  end   

  def create
    @user = User.create!(user_params)
    if @user.save
      redirect_to admins_path
    else
      render 'new'
    end
  end

  def confirm_order 
  end  

  def update_user  
    if current_user!= user.admin? && current_user!= user.shopkeeper?      
      current_user.update_attributes(user_type:0)
      current_user.orders.create(order:params[:order])
      redirect_to root_path
    end  
  end                                                                                                                                   
  
  private

  def user_params
   params.require(:user).permit(:first_name, :last_name,
  :phone_no,:user_type,:email,:password,:password_confirmation)
  end  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/shopkeepers_helper.rb
module ShopkeepersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/admins/index.html.erb
<div class="container">
  <div class="table-responsive">          
    <table class="table">
      <% @users.each do |user| %>
        <tr>
          <td><%=user.email%></td>
          <td><%=user.user_type%></td>  
        </tr>
      <% end %>    
    </table>
  </div>
  
  <div class="row">
    <div class="col-sm-6">
      <%=link_to "create", new_user_path %>
    </div>
  </div>  
</div>    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deliverysystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete,class: "logout" %>
    <% end %>
  </body>
</html>

app/views/users/confirm_order.html.erb
<h1>Click here to confirm your order </h1> 
  
  <%= form_tag('/admin/users/update_user') do %>
    <h5>confirm the order</h5><%=check_box_tag :confirmed, true, false%>
    <%=submit_tag("Submit")%>
  <%end%>  

   

app/views/users/index.html.erb
<h1>Choose item from the menu </h1>     
  <%= form_tag('/admin/users/confirm_order') do %>
    <%=select_tag "order", options_from_collection_for_select(Item.all, "name", "name",readonly: true)%>
    <%=submit_tag("Submit")%>
  <% end %>  

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-3">
      <h2>Sign up</h2>
    </div>
      <div class="col-sm-5"></div>
  </div>
</div><br>

<%= form_for @user do |f| %>
  <div class="container">
    <div class="row">    
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :Firstname %><br />
          <%= f.text_field :first_name, autofocus: true %>
        </div>  
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :Lastname %><br />
          <%= f.text_field :last_name, autofocus: true %>
        </div>
      </div>
     
    <div class="row">  
      <div class="col-sm-4">
        <div class="form-group">
         <%= f.label :email %><br/>
         <%= f.email_field :email, autofocus: true %>
        </div>  
      </div>
  
      <div class="col-sm-4">
        <div class="form-group">
         <%= f.label :password %><br/>
         <%= f.password_field :password, autofocus: true %>
        </div>  
      </div>

      <div class="col-sm-4">
        <div class="form-group">
         <%= f.label :password %><br/>
         <%= f.password_field :password_confirmation, autofocus: true %>
        </div>  
      </div>  
    </div>          
    <div class="row">   
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :Choose_role %><br/>
          <%= f.select "user_type", User.user_types.keys%>
        </div>
      </div> 
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.submit "Sign up" %>
        </div>  
      </div>
    </div> 
  </div>     
<% end %>